export const galleryData = [
  {
    id: "gallery-lab-moments",
    year: 2024,
    category: "Lab Moments",
    displayOrder: 0,
    hideCaptions: false,
    legacyQueries: [
      { year: 2024, category: "Year Archive" },
      { year: 2023, category: "Year Archive" },
    ],
    title: {
      ko: "Lab Moments",
      en: "Lab Moments",
    },
    description: {
      ko: "학회, 졸업, 송별회 등 연구실의 주요 활동 기록입니다.",
      en: "Major lab events including conferences, graduations, and farewell moments.",
    },
    coverImage: {
      src: "media/edited/gallery/lab-moments-cover.jpg",
      alt: {
        ko: "Lab Moments 아카이브 대표 사진",
        en: "Lab Moments archive cover photo",
      },
    },
    images: [
      {
        id: "lab-moments-professors-birthday-2024",
        year: 2024,
        src: "media/edited/gallery/lab-moments-professors-birthday-2024.jpg",
        alt: { ko: "교수님 생신", en: "Professor's Birthday" },
        caption: { ko: "교수님 생신", en: "Professor's Birthday" },
      },
      {
        id: "lab-moments-year-end-party-2024",
        year: 2024,
        src: "media/edited/gallery/lab-moments-year-end-party-2024.jpg",
        alt: { ko: "송년회", en: "Year-end Party" },
        caption: { ko: "송년회", en: "Year-end Party" },
      },
      {
        id: "lab-moments-kalas-2024",
        year: 2024,
        src: "media/edited/gallery/lab-moments-kalas-2024.jpg",
        alt: { ko: "KALAS", en: "KALAS" },
        caption: { ko: "KALAS", en: "KALAS" },
      },
      {
        id: "lab-moments-ksbmb-fibrosis-2024",
        year: 2024,
        src: "media/edited/gallery/lab-moments-ksbmb-fibrosis-2024.jpg",
        alt: {
          ko: "KSBMB 섬유화연구분과 심포지움",
          en: "KSBMB Fibrosis Division Symposium",
        },
        caption: {
          ko: "KSBMB 섬유화연구분과 심포지움",
          en: "KSBMB Fibrosis Division Symposium",
        },
      },
      {
        id: "lab-moments-farewell-gyeongmin-2024",
        year: 2024,
        src: "media/edited/gallery/lab-moments-farewell-gyeongmin-2024.jpg",
        alt: { ko: "경민 송별회", en: "Farewell for Gyeongmin" },
        caption: { ko: "경민 송별회", en: "Farewell for Gyeongmin" },
      },
      {
        id: "lab-moments-farewell-yeonggyeong-2024",
        year: 2024,
        src: "media/edited/gallery/lab-moments-farewell-yeonggyeong-2024.jpg",
        alt: { ko: "연경 송별회", en: "Farewell for Yeonggyeong" },
        caption: { ko: "연경 송별회", en: "Farewell for Yeonggyeong" },
      },
      {
        id: "lab-moments-jeju-ksmcb-2023",
        year: 2023,
        src: "media/edited/gallery/lab-moments-jeju-ksmcb-2023.jpg",
        alt: { ko: "JEJU KSMCB", en: "JEJU KSMCB" },
        caption: { ko: "JEJU KSMCB", en: "JEJU KSMCB" },
      },
      {
        id: "lab-moments-kmpc-workshop-2023",
        year: 2023,
        src: "media/edited/gallery/lab-moments-kmpc-workshop-2023.jpg",
        alt: { ko: "KMPC 워크숍", en: "KMPC Workshop" },
        caption: { ko: "KMPC 워크숍", en: "KMPC Workshop" },
      },
      {
        id: "lab-moments-busan-ksbmb-2023",
        year: 2023,
        src: "media/edited/gallery/lab-moments-busan-ksbmb-2023.jpg",
        alt: { ko: "BUSAN KSBMB", en: "BUSAN KSBMB" },
        caption: { ko: "BUSAN KSBMB", en: "BUSAN KSBMB" },
      },
      {
        id: "lab-moments-graduation-sihyeon-jiyeon-2023",
        year: 2023,
        src: "media/edited/gallery/lab-moments-graduation-sihyeon-jiyeon-2023.jpg",
        alt: { ko: "졸업 (시현 & 지연)", en: "Graduation (Sihyeon & Jiyeon)" },
        caption: { ko: "졸업 (시현 & 지연)", en: "Graduation (Sihyeon & Jiyeon)" },
      },
      {
        id: "lab-moments-farewell-2023",
        year: 2023,
        src: "media/edited/gallery/lab-moments-farewell-2023.jpg",
        alt: { ko: "송별회", en: "Farewell" },
        caption: { ko: "송별회", en: "Farewell" },
      },
      {
        id: "lab-moments-farewell-2020",
        year: 2020,
        src: "media/edited/gallery/lab-moments-farewell-2020.jpg",
        alt: { ko: "송별회", en: "Farewell" },
        caption: { ko: "송별회", en: "Farewell" },
      },
      {
        id: "lab-moments-jeju-ksbmb-2019",
        year: 2019,
        src: "media/edited/gallery/lab-moments-jeju-ksbmb-2019.jpg",
        alt: { ko: "JEJU KSBMB", en: "JEJU KSBMB" },
        caption: { ko: "JEJU KSBMB", en: "JEJU KSBMB" },
      },
      {
        id: "lab-moments-farewell-2018",
        year: 2018,
        src: "media/edited/gallery/lab-moments-farewell-2018.jpg",
        alt: { ko: "송별회", en: "Farewell" },
        caption: { ko: "송별회", en: "Farewell" },
      },
      {
        id: "lab-moments-graduation-kyounghye-yoonji-2018",
        year: 2018,
        src: "media/edited/gallery/lab-moments-graduation-kyounghye-yoonji-2018.jpg",
        alt: { ko: "졸업 (경혜 & 윤지)", en: "Graduation (Kyounghye & Yoonji)" },
        caption: { ko: "졸업 (경혜 & 윤지)", en: "Graduation (Kyounghye & Yoonji)" },
      },
      {
        id: "lab-moments-ksmcb-2016",
        year: 2016,
        src: "media/edited/gallery/lab-moments-ksmcb-2016.jpg",
        alt: { ko: "KSMCB", en: "KSMCB" },
        caption: { ko: "KSMCB", en: "KSMCB" },
      },
    ],
  },
  {
    id: "gallery-lab-daily",
    year: 2024,
    category: "Lab Daily",
    displayOrder: 1,
    hideCaptions: true,
    legacyQuery: {
      category: "Lab Life",
    },
    title: {
      ko: "Lab Daily",
      en: "Lab Daily",
    },
    description: {
      ko: "연구실의 일상과 가벼운 순간들을 모은 사진입니다.",
      en: "Everyday lab snapshots and lighter moments.",
    },
    coverImage: {
      src: "media/edited/gallery/lab-daily-cover.jpg",
      alt: {
        ko: "Lab Daily 아카이브 대표 사진",
        en: "Lab Daily archive cover photo",
      },
    },
    images: [
      {
        id: "lab-daily-hr-sem-2024",
        year: 2024,
        src: "media/edited/gallery/lab-daily-hr-sem-2024.jpg",
        alt: { ko: "HR SEM", en: "HR SEM" },
        caption: { ko: "HR SEM", en: "HR SEM" },
      },
      {
        id: "lab-daily-mng-ladder-2024",
        year: 2024,
        src: "media/edited/gallery/lab-daily-mng-ladder-2024.jpg",
        alt: { ko: "MNG 사다리", en: "MNG Ladder" },
        caption: { ko: "MNG 사다리", en: "MNG Ladder" },
      },
      {
        id: "lab-daily-snapshot-2024",
        year: 2024,
        src: "media/edited/gallery/lab-daily-snapshot-2024.jpg",
        alt: { ko: "ㅎㅎ", en: "Lab Snapshot" },
        caption: { ko: "ㅎㅎ", en: "Lab Snapshot" },
      },
      {
        id: "lab-daily-dinner-2024",
        year: 2024,
        src: "media/edited/gallery/lab-daily-dinner-2024.jpg",
        alt: { ko: "회식", en: "Lab Dinner" },
        caption: { ko: "회식", en: "Lab Dinner" },
      },
      {
        id: "lab-daily-busan-2024",
        year: 2024,
        src: "media/edited/gallery/lab-daily-busan-2024.jpg",
        alt: { ko: "Busan", en: "Busan" },
        caption: { ko: "Busan", en: "Busan" },
      },
      {
        id: "lab-daily-busan-2-2024",
        year: 2024,
        src: "media/edited/gallery/lab-daily-busan-2-2024.jpg",
        alt: { ko: "Busan", en: "Busan" },
        caption: { ko: "Busan", en: "Busan" },
      },
      {
        id: "lab-daily-jeju-2024",
        year: 2024,
        src: "media/edited/gallery/lab-daily-jeju-2024.jpg",
        alt: { ko: "Jeju", en: "Jeju" },
        caption: { ko: "Jeju", en: "Jeju" },
      },
    ],
  },
];
