export const publicationsData = [
  {
    "id": "legacy-2025-cilk1-is-essential-for-mesenchymal-cilia-mai-1",
    "year": 2025,
    "title": "Cilk1 is essential for mesenchymal cilia maintenance and epithelial-mesenchymal crosstalk in intestinal villus morphogenesis",
    "authors": "Song J., Je S.Y., Lee B., and Ko H.W.",
    "journal": "학술지 정보 확인 필요",
    "theme": "Cilia Biology",
    "featured": true,
    "verified": true,
    "url": "https://www.clinicalkey.com/#!/content/playContent/1-s2.0-S2352345X25002139?returnurl=https:%2F%2Flinkinghub.elsevier.com%2Fretrieve%2Fpii%2FS2352345X25002139%3Fshowall%3Dtrue&referrer=https:%2F%2Fpubmed.ncbi.nlm.nih.gov%2F"
  },
  {
    "id": "legacy-2025-ebastine-mediated-destabilization-of-e3-liga-2",
    "year": 2025,
    "title": "Ebastine-mediated destabilization of E3 ligase MKRN1 protects against metabolic dysfunction-associated steatohepatitis",
    "authors": "Kim S., Han H.J., Rho H., Kang S., Mukherjee S., Kim J., Kim D., Ko H.W., Lim S.M., Im S.S., Chung J.Y., and Song J.",
    "journal": "학술지 정보 확인 필요",
    "theme": "Metabolic Disease",
    "featured": true,
    "verified": true,
    "url": "https://link.springer.com/article/10.1007/s00018-024-05535-2"
  },
  {
    "id": "legacy-2025-ebastine-mediated-shank2-establishes-auditor-3",
    "year": 2025,
    "title": "Ebastine-mediated SHANK2 establishes auditory hair bundle architecture essential for mammalian hearing steatohepatitis",
    "authors": "Choi H.S., Park H., Min H., Kim K.S., Kim S.M., Li J., Liu C., Ko H.W., Lee M.G., Song L., Zhao B., and Bok J.",
    "journal": "학술지 정보 확인 필요",
    "theme": "Metabolic Disease",
    "featured": true,
    "verified": true,
    "url": "https://www.pnas.org/doi/10.1073/pnas.2426646122?url_ver=Z39.88-2003&rfr_id=ori%3Arid%3Acrossref.org&rfr_dat=cr_pub++0pubmed"
  },
  {
    "id": "legacy-2025-opposing-regulation-of-the-k63-linked-polyub-4",
    "year": 2025,
    "title": "Opposing regulation of the K63-linked polyubiquitination of RIPK3 by SMURF1 and USP5 in necroptosis",
    "authors": "Hwang C.H., Lee M., Kim J.W., Nam Y.W., Hwang G., Ryu H.S., Seo J., Lee E.W., Ko H.W., and Song J.",
    "journal": "학술지 정보 확인 필요",
    "theme": "Archive",
    "featured": true,
    "verified": true,
    "url": "https://www.nature.com/articles/s41467-025-62723-9"
  },
  {
    "id": "legacy-2025-progressive-tooth-pattern-changes-in-cilk1-d-5",
    "year": 2025,
    "title": "Progressive Tooth Pattern Changes in Cilk1-Deficient Mice Depending on Hedgehog Signaling",
    "authors": "Kyeong M., Jeong J.K., Adasooriya D., Kan S., Kim J., Song J., Park S., Je S.Y., Moon S.J., Park Y.B., Ko H.W. *, Cho E.S. *, and Cho S.W.",
    "journal": "학술지 정보 확인 필요",
    "theme": "Cilia Biology",
    "featured": true,
    "verified": false,
    "url": ""
  },
  {
    "id": "legacy-2025-the-pnpla3-i148m-variant-is-associated-with--6",
    "year": 2025,
    "title": "The PNPLA3 I148M variant is associated with immune cell infiltration and advanced fibrosis in MASLD: a prospective genotype-phenotype study",
    "authors": "Lee J., Cha J.H., Cho H.S., Yang K., Yang H., Nam H., Byun M.Y., Cho S.K., Park J., Ko H.W., Yang S.W., Sung P.S., and Bae S.H.",
    "journal": "학술지 정보 확인 필요",
    "theme": "Aging & Fibrosis",
    "featured": true,
    "verified": true,
    "url": "https://doi.org/10.1007/s00535-025-02285-1"
  },
  {
    "id": "legacy-2024-distinct-roles-of-centriole-distal-appendage-7",
    "year": 2024,
    "title": "Distinct roles of centriole distal appendage proteins in ciliary assembly and disassembly",
    "authors": "Su-yeon Je, Hyuk Wan Ko",
    "journal": "학술지 정보 확인 필요",
    "theme": "Cilia Biology",
    "featured": false,
    "verified": true,
    "url": "https://doi.org/10.1186/s12964-024-01962-7"
  },
  {
    "id": "legacy-2024-tmem132a-regulates-wnt-catenin-signaling-thr-8",
    "year": 2024,
    "title": "TMEM132A regulates Wnt/β-catenin signaling through stabilizing LRP6 during mouse embryonic development",
    "authors": "Shin Ae Oh, Jiyeon Jeon, Su-yeon Je, Seoyoung Kim, Joohyun Jung, Hyuk Wan Ko",
    "journal": "학술지 정보 확인 필요",
    "theme": "Archive",
    "featured": false,
    "verified": true,
    "url": "https://doi.org/10.1186/s12964-024-01855-9"
  },
  {
    "id": "legacy-2024-a-novel-indole-derivative-2-3-1-benzylsulfon-9",
    "year": 2024,
    "title": "A novel indole derivative, 2-{3-[1-(benzylsulfonyl)piperidin-4-yl]-2-methyl-1H-indol-1-yl}-1-(pyrrolidin-1-yl)ethenone, suppresses hedgehog signaling and drug-resistant tumor growth",
    "authors": "Joo Hyun Jung, Hwayoung Lee, Jiyeon Jeon, Yoon Ji Lee, Hossam Nada, Minkyoung Kim, Hankyu Lee, Deepak Bhattarai, Kyeong Lee, Hyuk Wan Ko",
    "journal": "학술지 정보 확인 필요",
    "theme": "Drug Discovery",
    "featured": false,
    "verified": true,
    "url": "https://onlinelibrary.wiley.com/doi/full/10.1002/ardp.202400218"
  },
  {
    "id": "legacy-2023-egg-microneedle-for-transdermal-delivery-of--10",
    "year": 2023,
    "title": "Egg Microneedle for Transdermal Delivery of Active Liraglutide",
    "authors": "Jeongyun You, Seorin Juhng, Jieun Song, Jihyun Park, Mingyu Jang, Geonwoo Kang, Huisuk Yang, Hye Su Mi, Jiwoo Shin, Seri Lee, Hyuk Wan Ko, Hyungil Jung",
    "journal": "학술지 정보 확인 필요",
    "theme": "Archive",
    "featured": false,
    "verified": true,
    "url": "https://pubmed.ncbi.nlm.nih.gov/36617627/"
  },
  {
    "id": "legacy-2023-fabrication-of-liraglutide-encapsulated-trip-11",
    "year": 2023,
    "title": "Fabrication of liraglutide-encapsulated triple layer hyaluronic acid microneedles (TLMs) for the treatment of obesity",
    "authors": "Seorin Juhng, Jieun Song, Jeongyun You, Jihyun Park, Huisuk Yang, Mingyu Jang, Geonwoo Kang, Jiwoo Shin, Hyuk Wan Ko and Hyungil Jung",
    "journal": "학술지 정보 확인 필요",
    "theme": "Metabolic Disease",
    "featured": false,
    "verified": true,
    "url": "https://pubs.rsc.org/en/content/articlelanding/2023/lc/d2lc01084d"
  },
  {
    "id": "legacy-2022-tissue-specific-requirement-of-sodium-channe-12",
    "year": 2022,
    "title": "Tissue-specific requirement of sodium channel and clathrin linker 1 (Sclt1) for ciliogenesis during limb development",
    "authors": "Hankyu Lee, Kyeong-Hye Moon, Kyeong-Hye Moon, Jieun Song, Jieun Song, Suyeon Je, Suyeon Je, Jinwoong Bok, Jinwoong Bok, Hyuk Wan Ko, Hyuk Wan Ko",
    "journal": "학술지 정보 확인 필요",
    "theme": "Archive",
    "featured": false,
    "verified": true,
    "url": "https://www.frontiersin.org/journals/cell-and-developmental-biology/articles/10.3389/fcell.2022.1058895/full"
  },
  {
    "id": "legacy-2022-klc3-regulates-ciliary-trafficking-and-cyst--13",
    "year": 2022,
    "title": "KLC3 Regulates Ciliary Trafficking and Cyst Progression in CILK1 Deficiency-Related Polycystic Kidney Disease",
    "authors": "Gyuyeong Rah, Hwayeon Cha, Joohee Kim, Jieun Song, Hyunho Kim, Yun Kyu Oh, Curie Ahn, Minyong Kang, Jongmin Kim, Kyung Hyun Yoo, Min Jung Kim, Hyuk Wan Ko, Je Yeong Ko, Jong Hoon Park",
    "journal": "학술지 정보 확인 필요",
    "theme": "Cilia Biology",
    "featured": false,
    "verified": true,
    "url": "https://pubmed.ncbi.nlm.nih.gov/35961787/"
  },
  {
    "id": "legacy-2021-upregulated-guanine-deaminase-is-involved-in-14",
    "year": 2021,
    "title": "Upregulated Guanine Deaminase Is Involved in Hyperpigmentation of Seborrheic Keratosis via Uric Acid Release",
    "authors": "Kyung Ah Cheong, In Sup Kil, Hyuk Wan Ko, Ai-Young Lee",
    "journal": "학술지 정보 확인 필요",
    "theme": "Archive",
    "featured": false,
    "verified": true,
    "url": "https://pubmed.ncbi.nlm.nih.gov/34830382/"
  },
  {
    "id": "legacy-2020-cell-cycle-related-kinase-is-a-crucial-regul-15",
    "year": 2020,
    "title": "Cell cycle-related kinase is a crucial regulator for ciliogenesis and Hedgehog signaling in embryonic mouse lung development",
    "authors": "Hankyu Lee, Hyuk Wan Ko",
    "journal": "학술지 정보 확인 필요",
    "theme": "Cilia Biology",
    "featured": false,
    "verified": true,
    "url": "https://pubmed.ncbi.nlm.nih.gov/32317081/"
  },
  {
    "id": "legacy-2020-combination-of-pd-l1-and-pvr-determines-sens-16",
    "year": 2020,
    "title": "Combination of PD-L1 and PVR determines sensitivity to PD-1 blockade",
    "authors": "Bo Ryeong Lee, Sehyun Chae, Jihyun Moon, Myeong Joon Kim, Hankyu Lee, Hyuk Wan Ko, Byoung Chul Cho, Hyo Sup Shim, Daehee Hwang, Hye Ryun Kim, Sang-Jun Ha",
    "journal": "학술지 정보 확인 필요",
    "theme": "Archive",
    "featured": false,
    "verified": true,
    "url": "https://pubmed.ncbi.nlm.nih.gov/32554931/"
  },
  {
    "id": "legacy-2020-autophagy-induction-promotes-renal-cyst-grow-17",
    "year": 2020,
    "title": "Autophagy induction promotes renal cyst growth in polycystic kidney disease",
    "authors": "Eun Ji Lee, Je Yeong Ko, Sumin Oh, Jaehee Jun, Hyowon Mun, Chae Ji Lim, Seungwoon Seo, Hyuk Wan Ko, Hyunho Kim, Yun Kyu Oh, Curie Ahn, Minyong Kang, Min Jung Kim, Kyung Hyun Yoo, Goo Taeg Oh, Jong Hoon Park",
    "journal": "학술지 정보 확인 필요",
    "theme": "Archive",
    "featured": false,
    "verified": true,
    "url": "https://pubmed.ncbi.nlm.nih.gov/32949996/"
  },
  {
    "id": "legacy-2020-dysregulation-of-sonic-hedgehog-signaling-ca-18",
    "year": 2020,
    "title": "Dysregulation of sonic hedgehog signaling causes hearing loss in ciliopathy mouse models",
    "authors": "Kyeong-Hye Moon, Ji-Hyun Ma, Hyehyun Min, Heiyeun Koo, HongKyung Kim, Hyuk Wan Ko, Jinwoong Bok",
    "journal": "학술지 정보 확인 필요",
    "theme": "Sensory Biology",
    "featured": false,
    "verified": true,
    "url": "https://elifesciences.org/articles/56551"
  },
  {
    "id": "legacy-2019-activation-of-sonic-hedgehog-signaling-by-a--19",
    "year": 2019,
    "title": "Activation of sonic hedgehog signaling by a Smoothened agonist restores congenital defects in mouse models of endocrine-cerebro-osteodysplasia syndrome",
    "authors": "Jeong-Oh Shin, Jieun Song, Han Seul Choi, Jisu Lee, Kyeong Lee, Hyuk Wan Ko, Jinwoong Bok",
    "journal": "학술지 정보 확인 필요",
    "theme": "Cilia Biology",
    "featured": false,
    "verified": true,
    "url": "https://pubmed.ncbi.nlm.nih.gov/31662288/"
  },
  {
    "id": "legacy-2019-fibroblast-growth-factor-receptor-influences-20",
    "year": 2019,
    "title": "Fibroblast growth factor receptor influences primary cilium length through an interaction with intestinal cell kinase",
    "authors": "Michaela Kunova Bosakova, Alexandru Nita, Tomas Gregor, Miroslav Varecha, Iva Gudernova, Bohumil Fafilek, Tomas Barta, Neha Basheer, Sara P Abraham, Lukas Balek, Marketa Tomanova, Jana Fialova Kucerova, Juraj Bosak, David Potesil, Jennifer Zieba, Jieun Song, Peter Konik, Sohyun Park, Ivan Duran, Zbynek Zdrahal, David Smajs, Gert Jansen, Zheng Fu, Hyuk Wan Ko, Ales Hampl, Lukas Trantirek, Deborah Krakow, Pavel Krejci",
    "journal": "학술지 정보 확인 필요",
    "theme": "Archive",
    "featured": false,
    "verified": true,
    "url": "https://pubmed.ncbi.nlm.nih.gov/30782830/"
  },
  {
    "id": "legacy-2019-multilayer-fabrication-of-unobtrusive-poly-d-21",
    "year": 2019,
    "title": "Multilayer fabrication of unobtrusive poly(dimethylsiloxane) nanobrush for tunable cell adhesion",
    "authors": "Soo Sang Chae, Joo Hyun Jung, Won Jin Choi, Joung Kyu Park, Hong Koo Baik, Jongjin Jung & Hyuk Wan Ko",
    "journal": "학술지 정보 확인 필요",
    "theme": "Archive",
    "featured": false,
    "verified": true,
    "url": "https://www.nature.com/articles/s41598-018-37893-w"
  },
  {
    "id": "legacy-2018-repeated-restraint-stress-promotes-hippocamp-22",
    "year": 2018,
    "title": "Repeated restraint stress promotes hippocampal neuronal cell ciliogenesis and proliferation in mice",
    "authors": "Kyounghye Lee, Hyuk Wan Ko",
    "journal": "학술지 정보 확인 필요",
    "theme": "Archive",
    "featured": false,
    "verified": true,
    "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC6333620/"
  },
  {
    "id": "legacy-2018-sauchinone-controls-hepatic-cholesterol-home-23",
    "year": 2018,
    "title": "Sauchinone controls hepatic cholesterol homeostasis by the negative regulation of PCSK9 transcriptional network",
    "authors": "Hee-Sung Chae, Byoung Hoon You, Dong-Yeop Kim, Hankyu Lee, Hyuk Wan Ko, Hyun-Jeong Ko, Young Hee Choi, Sun Shim Choi & Young-Won Chin",
    "journal": "학술지 정보 확인 필요",
    "theme": "Archive",
    "featured": false,
    "verified": true,
    "url": "https://www.nature.com/articles/s41598-018-24935-6"
  },
  {
    "id": "legacy-2017-pegylated-hyaluronic-acid-coated-liposome-fo-24",
    "year": 2017,
    "title": "PEGylated hyaluronic acid-coated liposome for enhanced in vivo efficacy of sorafenib via active tumor cell targeting and prolonged systemic exposure",
    "authors": "Lingxuan Mo, Jae Geun Song, Hankyu Lee, Mengjia Zhao, Hyeon Young Kim, Yoon Ji Lee, Hyuk Wan Ko, Hyo-Kyung Han",
    "journal": "학술지 정보 확인 필요",
    "theme": "Archive",
    "featured": false,
    "verified": true,
    "url": "https://pubmed.ncbi.nlm.nih.gov/29248675/"
  },
  {
    "id": "legacy-2017-capsaicin-prevents-degeneration-of-dopamine--25",
    "year": 2017,
    "title": "Capsaicin prevents degeneration of dopamine neurons by inhibiting glial activation and oxidative stress in the MPTP model of Parkinson's disease",
    "authors": "Young C Chung, Jeong Y Baek, Sang R Kim, Hyuk W Ko, Eugene Bok, Won-Ho Shin, So-Yoon Won, Byung K Jin",
    "journal": "학술지 정보 확인 필요",
    "theme": "Neurodegeneration",
    "featured": false,
    "verified": true,
    "url": "https://pubmed.ncbi.nlm.nih.gov/28255166/"
  },
  {
    "id": "legacy-2017-cell-cycle-related-kinase-ccrk-regulates-cil-26",
    "year": 2017,
    "title": "Cell Cycle-Related Kinase (CCRK) regulates ciliogenesis and Hedgehog signaling in mice",
    "authors": "Ashley Snouffer, Desmond Brown, Hankyu Lee, Jonathon Walsh, Floria Lupu, Ryan Norman, Karl Lechtreck, Hyuk Wan Ko, Jonathan Eggenschwiler",
    "journal": "학술지 정보 확인 필요",
    "theme": "Cilia Biology",
    "featured": false,
    "verified": true,
    "url": "https://pubmed.ncbi.nlm.nih.gov/28817564/"
  },
  {
    "id": "legacy-2017-design-synthesis-and-biological-evaluation-o-27",
    "year": 2017,
    "title": "Design, synthesis, and biological evaluation of structurally modified isoindolinone and quinazolinone derivatives as hedgehog pathway inhibitors.",
    "authors": "Deepak Bhattarai, Joo Hyun Jung, Seunghyeon Han, Hankyu Lee, Soo Jin Oh, Hyuk Wan Ko, Kyeong Lee",
    "journal": "학술지 정보 확인 필요",
    "theme": "Cilia Biology",
    "featured": false,
    "verified": true,
    "url": "https://pubmed.ncbi.nlm.nih.gov/27810591/"
  },
  {
    "id": "legacy-2017-injury-stimulated-sonic-hedgehog-expression--28",
    "year": 2017,
    "title": "Injury-stimulated Sonic hedgehog expression in microglia contributes to neuroinflammatory response in the MPTP model of Parkinson's disease",
    "authors": "Jeong Hwi Lee, Young Cheul Chung, Eugene Bok, Hankyu Lee, Sue Hee Huh, Ji Eun Lee, Byung Kwan Jin, Hyuk Wan Ko",
    "journal": "학술지 정보 확인 필요",
    "theme": "Cilia Biology",
    "featured": false,
    "verified": true,
    "url": "https://pubmed.ncbi.nlm.nih.gov/27899315/"
  },
  {
    "id": "legacy-2016-an-inactivating-mutation-in-intestinal-cell--29",
    "year": 2016,
    "title": "An inactivating mutation in intestinal cell kinase, ICK, impairs hedgehog signaling and causes short rib-polydactyly syndrome.",
    "authors": "S Paige Taylor, Michaela Kunova Bosakova, Miroslav Varecha, Lukas Balek, Tomas Barta, Lukas Trantirek, Iva Jelinkova, Ivan Duran, Iva Vesela, Kimberly N Forlenza, Jorge H Martin, Ales Hampl, Michael Bamshad, Deborah Nickerson, Margie L Jaworski, Jieun Song, Hyuk Wan Ko, Daniel H Cohn, Deborah Krakow, Pavel Krejci",
    "journal": "학술지 정보 확인 필요",
    "theme": "Cilia Biology",
    "featured": false,
    "verified": true,
    "url": "https://pubmed.ncbi.nlm.nih.gov/27466187/"
  },
  {
    "id": "legacy-2016-ciliary-smoothened-mediated-noncanonical-hed-30",
    "year": 2016,
    "title": "Ciliary smoothened-mediated noncanonical hedgehog signaling promotes tubulin acetylation.",
    "authors": "Hankyu Lee, Hyuk Wan Ko",
    "journal": "학술지 정보 확인 필요",
    "theme": "Cilia Biology",
    "featured": false,
    "verified": true,
    "url": "https://pubmed.ncbi.nlm.nih.gov/27793670/"
  },
  {
    "id": "legacy-2016-paclitaxel-nanodiamond-nanocomplexes-enhance-31",
    "year": 2016,
    "title": "Paclitaxel-Nanodiamond Nanocomplexes Enhance Aqueous Dispersibility and Drug Retention in Cells.",
    "authors": "Dae Gon Lim, Joo Hyun Jung, Hyuk Wan Ko, Eunah Kang, Seong Hoon Jeong",
    "journal": "학술지 정보 확인 필요",
    "theme": "Archive",
    "featured": false,
    "verified": true,
    "url": "https://pubs.acs.org/doi/10.1021/acsami.6b08079"
  },
  {
    "id": "legacy-2016-sulforaphene-interferes-with-human-breast-ca-32",
    "year": 2016,
    "title": "Sulforaphene Interferes with Human Breast Cancer Cell Migration and Invasion through Inhibition of Hedgehog Signaling.",
    "authors": "Cheng Bao, Min Chae Kim, Jing Chen, Jieun Song, Hyuk Wan Ko, Hong Jin Lee",
    "journal": "학술지 정보 확인 필요",
    "theme": "Cilia Biology",
    "featured": false,
    "verified": true,
    "url": "https://pubs.acs.org/doi/10.1021/acs.jafc.6b02195"
  },
  {
    "id": "legacy-2015-effects-of-substrate-conductivity-on-cell-mo-33",
    "year": 2015,
    "title": "Effects of substrate conductivity on cell morphogenesis and proliferation using tailored, atomic layer deposition-grown ZnO thin films.",
    "authors": "Won Jin Choi, Jongjin Jung, Sujin Lee, Yoon Jang Chung, Cheol-Soo Yang, Young Kuk Lee, You-Seop Lee, Joung Kyu Park, Hyuk Wan Ko & Jeong-O Lee",
    "journal": "학술지 정보 확인 필요",
    "theme": "Archive",
    "featured": false,
    "verified": true,
    "url": "https://www.nature.com/articles/srep09974"
  },
  {
    "id": "legacy-2015-leptin-elongates-hypothalamic-neuronal-cilia-34",
    "year": 2015,
    "title": "Leptin Elongates Hypothalamic Neuronal Cilia via Transcriptional Regulation and Actin Destabilization.",
    "authors": "Gil Myoung Kang, Yu Mi Han, Hyuk Whan Ko, Joon Kim, Byung Chul Oh, Ijoo Kwon, Min-Seon Kim",
    "journal": "학술지 정보 확인 필요",
    "theme": "Cilia Biology",
    "featured": false,
    "verified": true,
    "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC4505059/"
  },
  {
    "id": "legacy-2015-primary-cilia-in-energy-balance-signaling-an-35",
    "year": 2015,
    "title": "Primary cilia in energy balance signaling and metabolic disorder.",
    "authors": "Hankyu Lee, Jieun Song, Joo Hyun Jung, Hyuk Wan Ko",
    "journal": "학술지 정보 확인 필요",
    "theme": "Metabolic Disease",
    "featured": false,
    "verified": true,
    "url": "https://pubmed.ncbi.nlm.nih.gov/26538252/"
  },
  {
    "id": "legacy-2015-trpv1-on-astrocytes-rescues-nigral-dopamine--36",
    "year": 2015,
    "title": "TRPV1 on astrocytes rescues nigral dopamine neurons in Parkinson's disease via CNTF.",
    "authors": "Nam J.H., Park E.S., Won S.Y., Lee Y.A., Kim K.I., Jeong J.Y., Baek J.Y., Cho E.J., Jin M., Chung Y.C., Lee B.D., Kim S.H., Kim E.G., Byun K., Lee B., Woo D.H., Lee C.J., Kim S.R., Bok E., Kim Y.S., Ahn T.B., Ko H.W, Brahmachari S., Pletinkova O., Troconso J.C., Dawson V.L., Dawson T.M., Jin B.K.",
    "journal": "학술지 정보 확인 필요",
    "theme": "Neurodegeneration",
    "featured": false,
    "verified": true,
    "url": "https://academic.oup.com/brain/article/138/12/3610/414707?login=false"
  },
  {
    "id": "legacy-2014-daidzein-suppresses-tumor-necrosis-factor-in-37",
    "year": 2014,
    "title": "Daidzein Suppresses Tumor Necrosis Factor-α Induced Migration and Invasion by Inhibiting Hedgehog/Gli1 Signaling in Human Breast Cancer Cells.",
    "authors": "Cheng Bao, Hyeju Namgung, Jaehoo Lee, Hyun-Chang Park, Jiwon Ko, Heejung Moon, Hyuk Wan Ko, Hong Jin Lee",
    "journal": "학술지 정보 확인 필요",
    "theme": "Cilia Biology",
    "featured": false,
    "verified": true,
    "url": "https://pubmed.ncbi.nlm.nih.gov/24724627/"
  },
  {
    "id": "legacy-2014-intestinal-cell-kinase-a-protein-associated--38",
    "year": 2014,
    "title": "Intestinal cell kinase, a protein associated with endocrine-cerebro-osteodysplasia syndrome, is a key regulator of cilia length and Hedgehog signaling.",
    "authors": "Heejung Moon, Jieun Song, Jeong-Oh Shin, Hankyu Lee, Hong-Kyung Kim, Jonathan T Eggenschwiller, Jinwoong Bok, Hyuk Wan Ko",
    "journal": "학술지 정보 확인 필요",
    "theme": "Cilia Biology",
    "featured": false,
    "verified": true,
    "url": "https://pubmed.ncbi.nlm.nih.gov/24853502/"
  },
  {
    "id": "legacy-2014-leptin-promoted-cilia-assembly-is-critical-f-39",
    "year": 2014,
    "title": "Leptin-promoted cilia assembly is critical for normal energy balance.",
    "authors": "Yu Mi Han, Gil Myoung Kang, Kyunghee Byun, Hyuk Wan Ko, Joon Kim, Mi-Seon Shin, Hyun-Kyong Kim, So Young Gil, Ji Hee Yu, Bonghee Lee, Min-Seon Kim",
    "journal": "학술지 정보 확인 필요",
    "theme": "Cilia Biology",
    "featured": false,
    "verified": true,
    "url": "https://pubmed.ncbi.nlm.nih.gov/24667636/"
  },
  {
    "id": "legacy-2014-pax3-function-is-required-specifically-for-i-40",
    "year": 2014,
    "title": "Pax3 function is required specifically for inner ear structures with melanogenic fates.",
    "authors": "Hongkyung Kim, Harinarayana Ankamreddy, Dong Jin Lee, Kyoung-Ah Kong, Hyuk Wan Ko, Myoung Hee Kim, Jinwoong Bok",
    "journal": "학술지 정보 확인 필요",
    "theme": "Archive",
    "featured": false,
    "verified": true,
    "url": "https://pubmed.ncbi.nlm.nih.gov/24565836/"
  },
  {
    "id": "legacy-2013-localization-of-primary-cilia-in-mouse-retin-41",
    "year": 2013,
    "title": "Localization of primary cilia in mouse retina.",
    "authors": "Yong-Kyu Kim, Jin Hyoung Kim, Young Suk Yu, Hyuk Wan Ko, Jeong Hun Kim",
    "journal": "학술지 정보 확인 필요",
    "theme": "Cilia Biology",
    "featured": false,
    "verified": true,
    "url": "https://pubmed.ncbi.nlm.nih.gov/23608602/"
  },
  {
    "id": "legacy-2012-the-primary-cilium-as-a-multiple-cellular-si-42",
    "year": 2012,
    "title": "The primary cilium as a multiple cellular signaling scaffold in development and disease.",
    "authors": "Hyuk Wan Ko",
    "journal": "학술지 정보 확인 필요",
    "theme": "Archive",
    "featured": false,
    "verified": true,
    "url": "https://pubmed.ncbi.nlm.nih.gov/22917026/"
  },
  {
    "id": "legacy-2011-fluoxetine-prevents-mptp-induced-loss-of-dop-43",
    "year": 2011,
    "title": "Fluoxetine prevents MPTP-induced loss of dopaminergic neurons by inhibiting microglial activation",
    "authors": "Young C Chung, Sang R Kim, Ju-Young Park, Eun S Chung, Keun W Park, So Y Won, Eugene Bok, Minyoung Jin, Eun S Park, Sung-Hwa Yoon, Hyuk W Ko, Yoon-Seong Kim, Byung K Jin",
    "journal": "학술지 정보 확인 필요",
    "theme": "Neurodegeneration",
    "featured": false,
    "verified": true,
    "url": "https://www.ncbi.nlm.nih.gov/pubmed/21288472"
  },
  {
    "id": "legacy-2011-nemo-nlk-phosphorylates-period-to-initiate-a-44",
    "year": 2011,
    "title": "NEMO/NLK phosphorylates PERIOD to initiate a time-delay phosphorylation circuit that sets circadian clock speed.",
    "authors": "Joanna C Chiu, Hyuk Wan Ko, Isaac Edery",
    "journal": "학술지 정보 확인 필요",
    "theme": "Circadian Biology",
    "featured": false,
    "verified": true,
    "url": "https://pubmed.ncbi.nlm.nih.gov/21514639/"
  },
  {
    "id": "legacy-2011-intraflagellar-transport-protein-122-antagon-45",
    "year": 2011,
    "title": "Intraflagellar transport protein 122 antagonizes Sonic Hedgehog signaling and controls ciliary localization of pathway components.",
    "authors": "Jian Qin, Yulian Lin, Ryan X Norman, Hyuk W Ko, Jonathan T Eggenschwiler",
    "journal": "학술지 정보 확인 필요",
    "theme": "Cilia Biology",
    "featured": false,
    "verified": true,
    "url": "https://pubmed.ncbi.nlm.nih.gov/21209331/"
  },
  {
    "id": "legacy-2010-a-hierarchical-phosphorylation-cascade-invol-46",
    "year": 2010,
    "title": "A hierarchical phosphorylation cascade involving proline-mediated kinases and GSK3-b/SGG regulates the timing of PERIOD nuclear entry.",
    "authors": "Hyuk Wan Ko, Eun Young Kim, Joanna Chiu, Jens T Vanselow, Achim Kramer, Isaac Edery",
    "journal": "학술지 정보 확인 필요",
    "theme": "Archive",
    "featured": false,
    "verified": true,
    "url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC2957474/"
  },
  {
    "id": "legacy-2010-the-role-of-neuroinflammation-on-the-pathoge-47",
    "year": 2010,
    "title": "The role of neuroinflammation on the pathogenesis of Parkinson's disease",
    "authors": "Young Cheul Chung, Hyuk Wan Ko, Eugene Bok, Eun Soo Park, Sue Hee Huh, Jin Han Nam, Byung Kwan Jin",
    "journal": "학술지 정보 확인 필요",
    "theme": "Neurodegeneration",
    "featured": false,
    "verified": true,
    "url": "https://pubmed.ncbi.nlm.nih.gov/20423606/"
  },
  {
    "id": "legacy-2010-two-distinct-modes-of-period-recruitment-ont-48",
    "year": 2010,
    "title": "Two distinct modes of PERIOD recruitment onto dCLOCK reveal a novel role for TIMELESS in circadian transcription.",
    "authors": "Woo Chul Sun, Eun Hee Jeong, Hyun-Jeong Jeong, Hyuk Wan Ko, Isaac Edery, Eun Young Kim",
    "journal": "학술지 정보 확인 필요",
    "theme": "Circadian Biology",
    "featured": false,
    "verified": true,
    "url": "https://pubmed.ncbi.nlm.nih.gov/20980603/"
  },
  {
    "id": "legacy-2010-broad-minded-links-cell-cycle-related-kinase-49",
    "year": 2010,
    "title": "Broad-minded links cell cycle-related kinase to cilia assembly and Hedgehog signal transduction.",
    "authors": "Hyuk Wan Ko, Ryan X Norman, John Tran, Kimberly P Fuller, Mitsunori Fukuda, Jonathan T Eggenschwiler",
    "journal": "학술지 정보 확인 필요",
    "theme": "Cilia Biology",
    "featured": false,
    "verified": true,
    "url": "https://pubmed.ncbi.nlm.nih.gov/20159594/"
  },
  {
    "id": "legacy-2009-analysis-of-hedgehog-signaling-in-mouse-intr-50",
    "year": 2009,
    "title": "Analysis of Hedgehog signaling in mouse intraflagellar transport mutants.",
    "authors": "Hyuk W Ko, Aimin Liu, Jonathan T Eggenschwiler",
    "journal": "학술지 정보 확인 필요",
    "theme": "Cilia Biology",
    "featured": false,
    "verified": true,
    "url": "https://pubmed.ncbi.nlm.nih.gov/20409825/"
  },
  {
    "id": "legacy-2009-tubby-like-tulp3-regulates-embryonic-pattern-51",
    "year": 2009,
    "title": "Tubby-like(TULP3) regulates embryonic patterning in the mouse through inhibition of Hedgehog signaling.",
    "authors": "Ryan X Norman, Hyuk W Ko, Viola Huang, Christine M Eun, Lisa L Abler, Zhen Zhang, Xin Sun, Jonathan T Eggenschwiler",
    "journal": "학술지 정보 확인 필요",
    "theme": "Cilia Biology",
    "featured": false,
    "verified": true,
    "url": "https://pubmed.ncbi.nlm.nih.gov/19286674/"
  },
  {
    "id": "legacy-2008-natural-variation-in-the-splice-site-strengt-52",
    "year": 2008,
    "title": "Natural variation in the splice site strength of a clock gene and species-specific thermal adaptation",
    "authors": "Kwang Huei Low, Cecilia Lim, Hyuk Wan Ko, Isaac Edery",
    "journal": "학술지 정보 확인 필요",
    "theme": "Archive",
    "featured": false,
    "verified": true,
    "url": "https://pubmed.ncbi.nlm.nih.gov/19109911/"
  },
  {
    "id": "legacy-2008-fkbp8-cell-autonomously-controls-neural-tube-53",
    "year": 2008,
    "title": "FKBP8 cell-autonomously controls neural tube patterning through a Gli2- and Kif3a-dependent mechanism",
    "authors": "Ahryon Cho, Hyuk W Ko, Jonathan T Eggenschwiler",
    "journal": "학술지 정보 확인 필요",
    "theme": "Archive",
    "featured": false,
    "verified": true,
    "url": "https://pubmed.ncbi.nlm.nih.gov/18590716/"
  },
  {
    "id": "legacy-2007-a-doubletime-kinase-binding-domain-on-the-dr-54",
    "year": 2007,
    "title": "A DOUBLETIME kinase binding domain on the Drosophila PERIOD protein is essential for its hyperphosphorylation, transcriptional repression, and circadian clock function",
    "authors": "Eun Young Kim, Hyuk Wan Ko, Wangjie Yu, Paul E Hardin, Isaac Edery",
    "journal": "학술지 정보 확인 필요",
    "theme": "Circadian Biology",
    "featured": false,
    "verified": true,
    "url": "https://pubmed.ncbi.nlm.nih.gov/17452449/"
  },
  {
    "id": "legacy-2007-cis-combination-of-the-classic-per-s-and-per-55",
    "year": 2007,
    "title": "Cis-combination of the classic per(S) and per(L) mutations results in arrhythmic Drosophila with ectopic accumulation of hyperphosphorylated PERIOD protein",
    "authors": "Hyuk Wan Ko, Suzanne DiMassa, Eun Young Kim, Kiho Bae, Isaac Edery",
    "journal": "학술지 정보 확인 필요",
    "theme": "Archive",
    "featured": false,
    "verified": true,
    "url": "https://pubmed.ncbi.nlm.nih.gov/18057324/"
  },
  {
    "id": "legacy-2005-analyzing-the-degradation-of-period-protein--56",
    "year": 2005,
    "title": "Analyzing the degradation of PERIOD protein by the ubiquitin-proteasome pathway in cultured Drosophila cells",
    "authors": "Hyuk Wan Ko, Isaac Edery",
    "journal": "학술지 정보 확인 필요",
    "theme": "Archive",
    "featured": false,
    "verified": true,
    "url": "https://pubmed.ncbi.nlm.nih.gov/15817301/"
  },
  {
    "id": "legacy-2002-role-for-slimb-in-the-degradation-of-drosoph-57",
    "year": 2002,
    "title": "Role for Slimb in the degradation of Drosophila Period protein phosphorylated by Doubletime",
    "authors": "Hyuk Wan Ko, Jin Jiang, Isaac Edery",
    "journal": "학술지 정보 확인 필요",
    "theme": "Archive",
    "featured": false,
    "verified": true,
    "url": "https://pubmed.ncbi.nlm.nih.gov/12442174/"
  },
  {
    "id": "legacy-2000-https-pubmed-ncbi-nlm-nih-gov-10964597-58",
    "year": 2000,
    "title": "https://pubmed.ncbi.nlm.nih.gov/10964597/",
    "authors": "H W Ko, K S Han, E Y Kim, B R Ryu, W J Yoon, Y K Jung, S U Kim, B J Gwag",
    "journal": "학술지 정보 확인 필요",
    "theme": "Archive",
    "featured": false,
    "verified": true,
    "url": "https://pubmed.ncbi.nlm.nih.gov/10820206/"
  },
  {
    "id": "legacy-2000-nt-4-5-exacerbates-free-radical-induced-neur-59",
    "year": 2000,
    "title": "NT-4/5 exacerbates free radical-induced neuronal necrosis in vitro and in vivo",
    "authors": "S J Won, E C Park, B R Ryu, H W Ko, S Sohn, H J Kwon, B J Gwag",
    "journal": "학술지 정보 확인 필요",
    "theme": "Neuroscience",
    "featured": false,
    "verified": true,
    "url": "https://pubmed.ncbi.nlm.nih.gov/10964597/"
  },
  {
    "id": "legacy-1999-nuclear-factor-kappa-b-mediated-kainate-neur-60",
    "year": 1999,
    "title": "Nuclear factor kappa B-mediated kainate neurotoxicity in the rat and hamster hippocampus.",
    "authors": "Won SJ, Ko HW, Kim EY, Park EC, Huh K, Jung NP, Choi I, Oh YK, Shin HC, Gwag BJ",
    "journal": "학술지 정보 확인 필요",
    "theme": "Archive",
    "featured": false,
    "verified": true,
    "url": "https://europepmc.org/article/med/10613499"
  },
  {
    "id": "legacy-1999-necrosis-and-apoptosis-after-retinal-ischemi-61",
    "year": 1999,
    "title": "Necrosis and apoptosis after retinal ischemia: involvement of NMDA-mediated excitotoxicity and p53",
    "authors": "C K Joo, J S Choi, H W Ko, K Y Park, S Sohn, M H Chun, Y J Oh, B J Gwag",
    "journal": "학술지 정보 확인 필요",
    "theme": "Neuroscience",
    "featured": false,
    "verified": true,
    "url": "https://pubmed.ncbi.nlm.nih.gov/10067975/"
  },
  {
    "id": "legacy-1999-phosphatidylinositol-3-kinase-mediated-regul-62",
    "year": 1999,
    "title": "Phosphatidylinositol 3-kinase-mediated regulation of neuronal apoptosis and necrosis by insulin and IGF-I",
    "authors": "B R Ryu, H W Ko, I Jou, J S Noh, B J Gwag",
    "journal": "학술지 정보 확인 필요",
    "theme": "Neuroscience",
    "featured": false,
    "verified": true,
    "url": "https://pubmed.ncbi.nlm.nih.gov/10380075/"
  },
  {
    "id": "legacy-1998-a-neuron-specific-gene-transfer-by-a-recombi-63",
    "year": 1998,
    "title": "A neuron-specific gene transfer by a recombinant defective Sindbis virus",
    "authors": "Byoung J Gwag, Eun Y Kim, Bo R Ryu, Seok J Won, Hyuk W Ko, Young J Oh, Young-Gyu Cho, Sang J Ha, Young C Sung",
    "journal": "학술지 정보 확인 필요",
    "theme": "Archive",
    "featured": false,
    "verified": true,
    "url": "https://www.sciencedirect.com/science/article/abs/pii/S0169328X98002514"
  },
  {
    "id": "legacy-1998-ca2-mediated-activation-of-c-jun-n-terminal--64",
    "year": 1998,
    "title": "Ca2+-mediated activation of c-Jun N-terminal kinase and nuclear factor kappa B by NMDA in cortical cell cultures",
    "authors": "H W Ko, K Y Park, H Kim, P L Han, Y U Kim, B J Gwag, E J Choi",
    "journal": "학술지 정보 확인 필요",
    "theme": "Archive",
    "featured": false,
    "verified": true,
    "url": "https://pubmed.ncbi.nlm.nih.gov/9751169/"
  },
  {
    "id": "legacy-1998-the-cdna-cloning-and-ontogeny-of-mouse-alpha-65",
    "year": 1998,
    "title": "The cDNA cloning and ontogeny of mouse alpha-synuclein",
    "authors": "L Hong, H W Ko, B J Gwag, E Joe, S Lee, Y T Kim, Y H Suh",
    "journal": "학술지 정보 확인 필요",
    "theme": "Archive",
    "featured": false,
    "verified": true,
    "url": "https://pubmed.ncbi.nlm.nih.gov/9601701/"
  }
];

export const publicationThemes = [
  "All",
  "Cilia Biology",
  "Metabolic Disease",
  "Archive",
  "Aging & Fibrosis",
  "Drug Discovery",
  "Sensory Biology",
  "Neurodegeneration",
  "Circadian Biology",
  "Neuroscience"
];
