export const publicationsData = [
  {
    id: "p2026-01",
    year: 2026,
    title: "Primary cilia metabolism in tissue aging",
    authors: "Ko HW, Park S, Kim J",
    journal: "Aging Cell",
    theme: "Aging",
    featured: true,
    url: "https://doi.org/10.0000/example-2026-01",
  },
  {
    id: "p2026-02",
    year: 2026,
    title: "Distal appendage proteins and ciliogenesis control",
    authors: "Lee M, Ko HW",
    journal: "Developmental Cell",
    theme: "Cilia",
    featured: false,
    url: "https://doi.org/10.0000/example-2026-02",
  },
  {
    id: "p2025-01",
    year: 2025,
    title: "Cilk1 is essential in intestinal villus morphogenesis",
    authors: "Song J, et al.",
    journal: "Cell Mol Gastroenterol Hepatol",
    theme: "Aging",
    featured: true,
    url: "https://doi.org/10.0000/example-2025-01",
  },
  {
    id: "p2025-02",
    year: 2025,
    title: "Hedgehog signaling rewires tooth patterning in Cilk1-deficient mice",
    authors: "Kyeong M, et al.",
    journal: "International Journal of Oral Science",
    theme: "Cilia",
    featured: false,
    url: "https://doi.org/10.0000/example-2025-02",
  },
  {
    id: "p2025-03",
    year: 2025,
    title: "MEGF8-mediated BMP signaling in craniosynostosis",
    authors: "Ko HW, et al.",
    journal: "Cell Death and Differentiation",
    theme: "Rare Disease",
    featured: true,
    url: "https://doi.org/10.0000/example-2025-03",
  },
  {
    id: "p2024-01",
    year: 2024,
    title: "CEP89 deficiency links mitophagy failure to obesity",
    authors: "Park S, Kim J, Ko HW",
    journal: "Nature Metabolism",
    theme: "Metabolism",
    featured: true,
    url: "https://doi.org/10.0000/example-2024-01",
  },
  {
    id: "p2024-02",
    year: 2024,
    title: "ER-mitochondria contact site signaling in adipocyte stress",
    authors: "Lee M, et al.",
    journal: "EMBO Reports",
    theme: "Metabolism",
    featured: false,
    url: "https://doi.org/10.0000/example-2024-02",
  },
  {
    id: "p2023-01",
    year: 2023,
    title: "Cilia proteome atlas across developmental stages",
    authors: "Jang S, et al.",
    journal: "Molecular Systems Biology",
    theme: "Cilia",
    featured: false,
    url: "https://doi.org/10.0000/example-2023-01",
  },
  {
    id: "p2023-02",
    year: 2023,
    title: "Functional screening of craniosynostosis variants",
    authors: "Choi E, Ko HW",
    journal: "Human Molecular Genetics",
    theme: "Rare Disease",
    featured: false,
    url: "https://doi.org/10.0000/example-2023-02",
  },
  {
    id: "p2022-01",
    year: 2022,
    title: "A cilia-centered model for metabolic adaptation",
    authors: "Ko HW, et al.",
    journal: "Trends in Endocrinology and Metabolism",
    theme: "Metabolism",
    featured: false,
    url: "https://doi.org/10.0000/example-2022-01",
  },
];

export const publicationThemes = ["All", "Cilia", "Rare Disease", "Metabolism", "Aging"];
